version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    container_name: db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: prod
    ports:
      - "5432:5432"
    volumes:
      - ./tests/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "testuser", "-d", "prod"]
      interval: 2s
      timeout: 1m
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: no

  newman:
    image: postman/newman:latest
    container_name: newman
    command: ["run",
              "/etc/newman/public-tests.json",
              "-e", "/etc/newman/env.json", "--verbose"]
    volumes:
      - ./tests:/etc/newman
    depends_on:
      - backend
    restart: no

volumes:
  db-data: