version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./tests/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./src/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  newman:
    image: postman/newman:latest
    container_name: newman
    command: ["run", "/etc/newman/public-tests.json"]
    volumes:
      - ./tests:/etc/newman
    depends_on:
      - backend
    environment:
      - base_url=http://backend:8080/api
    restart: no

volumes:
  db-data: