name: Run Backend and Postman Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run backend, DB and Postman tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
            DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
            mkdir -p $DOCKER_CONFIG/cli-plugins
            curl -SL https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64  -o $DOCKER_CONFIG/cli-plugins/docker-compose
            chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
            docker compose version

      - name: Build and start services
        run: |
          docker-compose up -d

      - name: Wait for services to start
        run: |
          sleep 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: |
          npm install -g newman

      - name: Run Postman tests
        run: |
          newman run tests/public-tests.json \
            --env-var "base_url=http://localhost:8080/api" \
            --reporters cli,json \
            --reporter-json-export result.json

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./result.json
